In [23]:
import numpy as np
# list and arrays
l1=[1,2,3,4]
l2=[5,6,7,8]
l3=[5,10,15]
l4=[1,2,3]
print(l1+l2)
a=np.array(l1)
b=np.array(l2)
c=np.array(l3)
d=np.array(l4)



# type
print(type(a))



#mathematical operations
print(np.multiply(a,b))
print(np.divide(c,d))
print(np.power(a,2))



#combine text
print("Addition of Two:",l1+l2)



#Implement np.sin(), log(), log2(), np.exp())
print(np.sin(a))
print(np.log(a))
print(np.log2(a))
print(np.exp(a))

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'numpy.ndarray'>
[ 5 12 21 32]
[5. 5. 5.]
[ 1  4  9 16]
Addition of Two: [1, 2, 3, 4, 5, 6, 7, 8]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
